swaggerUrl: ./config/swagger.yaml

controllerPackage: de.tum.sebis.restbrain.controllers

modelPackage: de.tum.sebis.restbrain.models

modelMappings:
  Pet: de.tum.sebis.restbrain.models.Pet

# allows environment to be develop, staging, production.  Production will not start if
# unimplemented models or methods are detected
environment: development

# loads all by default, or pick and choose
entityProcessors:
  - json
  - xml
  - yaml
